### PR TITLE
fix: price range is failing when there is no nft in db

### PR DESCRIPTION
**Pull request by AlefrankM**

### CODE REVIEW

**Review by mmiranda-stackit — COMMENTED** [review]
did you review the backend? the issue was in there

**Comment by AlefrankM** [comment]
@mmiranda-stackit I just did this and works

**Review by juliswer — DISMISSED** [review]
looks good

**Comment by mmiranda-stackit** [comment]
> 

I bet it works, but if you look at the console, you'll see a 500 error. My opinion is that we should not let the backend to fail, but just return undefined/default values

**Review by juliswer — APPROVED** [review]
Looks good

**Pull request merged**
